package com.workdatebase.work.entity.Status;

public enum EmailType {
    VERIFICATION_REQUEST,
    APPROVAL_NOTIFICATION,
    REJECTION_NOTIFICATION,
    SUBMISSION_APPROVAL_NOTIFICATION,
    SUBMISSION_REJECTION_NOTIFICATION
}
